apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
              required:
                - website_url
            status:
              type: object
              properties:
                phase:
                  type: string
                url:
                  type: string
  scope: Namespaced
  names:
    plural: dummysites
    singular: dummysite
    kind: DummySite
    shortNames:
      - ds