---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dummysite-controller
  namespace: default
rules:
  - apiGroups: ["stable.example.com"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["stable.example.com"]
    resources: ["dummysites/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummysite-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dummysite-controller
subjects:
  - kind: ServiceAccount
    name: dummysite-controller
    namespace: default