apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: backend
          image: shehzadkhuwaja/todoapp:latest
          env:
          - name: IMAGE_URL
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: IMAGE_URL
          - name: IMAGE_EXPIRY_MINUTES
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: IMAGE_EXPIRY_MINUTES
          - name: IMAGE_FILE
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: IMAGE_FILE
          - name: META_FILE
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: META_FILE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: PORT
          volumeMounts:
            - name: shared-image
              mountPath: /shared
