apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: todo-app
          image: shehzadkhuwaja/express-server