apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-generator
  namespace: project
spec:
  schedule: "*/1 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wikipedia-todo-generator
              image: shehzadkhuwaja/todo-cronjob:latest
              env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: todo-secret
                    key: PGPASSWORD
              - name: PGDATABASE
                valueFrom:
                  configMapKeyRef:
                    name: todo-backend-config
                    key: PGDATABASE
              - name: PGUSER
                valueFrom:
                  configMapKeyRef:
                    name: todo-backend-config
                    key: PGUSER
              - name: PGPORT
                valueFrom:
                  configMapKeyRef:
                    name: todo-backend-config
                    key: PGPORT
              - name: PGHOST
                valueFrom:
                  configMapKeyRef:
                    name: todo-backend-config
                    key: PGHOST
          restartPolicy: OnFailure
