apiVersion: v1
kind: ConfigMap
metadata:
  name: wikipedia-scripts
data:
  init-script.sh: |
    #!/bin/sh
    echo "Fetching Kubernetes Wikipedia page..."
    curl -L https://en.wikipedia.org/wiki/Kubernetes -o /usr/share/nginx/html/index.html
    echo "Initial page fetched successfully"
  
  sidecar-script.sh: |
    #!/bin/sh
    echo "Sidecar container started"
    while true; do
      # Generate random wait time between 300 and 900 seconds (5-15 minutes)
      WAIT_TIME=$((120 + RANDOM % 120))
      echo "Waiting for $WAIT_TIME seconds before fetching random Wikipedia page..."
      sleep $WAIT_TIME
      
      echo "Fetching random Wikipedia page..."
      curl -L https://en.wikipedia.org/wiki/Special:Random -o /usr/share/nginx/html/index.html
      echo "Random page fetched and updated at $(date)"
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikipedia-server
  labels:
    app: wikipedia-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikipedia-server
  template:
    metadata:
      labels:
        app: wikipedia-server
    spec:
      # Shared volume for the HTML content
      volumes:
      - name: shared-html
        emptyDir: {}
      - name: scripts
        configMap:
          name: wikipedia-scripts
          defaultMode: 0755
      
      # Init container to fetch the initial Kubernetes Wikipedia page
      initContainers:
      - name: init-wikipedia
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/init-script.sh"]
        volumeMounts:
        - name: shared-html
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /scripts
      
      # Main container serving the Wikipedia pages
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      # Sidecar container to periodically fetch random Wikipedia pages
      - name: wikipedia-updater
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/sidecar-script.sh"]
        volumeMounts:
        - name: shared-html
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: wikipedia-server
  labels:
    app: wikipedia-server
spec:
  type: ClusterIP
  selector:
    app: wikipedia-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

---
# Optional: Ingress for external access
# Uncomment and configure if you have an Ingress controller
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wikipedia-server
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: wikipedia.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: wikipedia-server
#             port:
#               number: 80