apiVersion: v1
kind: Pod
metadata:
  name: log-output-dep
  labels:
    app: log-output
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: log-writer
      image: shehzadkhuwaja/string-generator:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /shared
    - name: log-reader
      image: shehzadkhuwaja/string-reader:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: shared-logs
          mountPath: /shared
